# 服务配置
server:
  # 本地ip
  ip: 127.0.0.1
  # 本地端口
  port: 8012
  # 节点之间数据同步的时间间隔（单位：秒）
  syncTime: 2
  # 是否为主节点（1:是，0:不是）
  isMaster: 1

# nacos注册中心配置
nacos:
  # Nacos所在服务器IP/域名
  ipAddr: VM-8-12-centos
  contextPath: /nacos
  port: 8848
  scheme: http
  # 日志存储路径
  logDir: log
  # 缓存service信息的目录
  cacheDir: cache

# 数据库配置
db:
  # 访问密钥（放在请求头部）
  secretKey: test_secret_key
