# 服务配置
server:
  # 服务器公网ip
  ip: 127.0.0.1
  port: 8012
  # 节点之间数据同步的时间间隔（单位：秒）
  syncTime: 1
  # 是否以集群方式部署（1:是，0:否）
  isCluster: 1
  # 是否为主节点（1:是，0:否）
  isMaster: 1

# nacos注册中心配置
nacos:
  # 集群命名空间Id（）
  namespaceId: maybe-db
  # Nacos所在服务器IP/域名
  ipAddr: VM-8-12-centos
  contextPath: /nacos
  port: 8848
  scheme: http
  timeoutMs: 3000
  notLoadCacheAtStart: true
  rotateTime: 24h
  maxAge: 4
  logLevel: debug
  logDir: log
  cacheDir: cache
  # Nacos的账户和密码（Nacos开启密码验证的情况下使用）
  username: nacos
  password: nacos

# 数据库配置
db:
  # 访问密钥（放在请求头部）
  secretKey: test_secret_key
  # 是否开启持久化（1:是，0:否）
  isPersistent: 1
  # 数据持久化操作的时间间隔（单位：秒）
  persistentTime: 5
  # 持久化文件保存路径
  persistentPath: ./data.csv
  # 数据恢复策略（0:不进行数据恢复，1:从本地持久化文件中获取数据，2:从集群其他健康的主节点获取数据）
  recoveryStrategy: 2
