# 服务配置
server:
  ip: 127.0.0.1
  port: 8012

# nacos配置
nacos:
  ipAddr: VM-8-12-centos
  contextPath: /nacos
  port: 8848
  scheme: http

# 数据库配置
db:
  # 访问密钥（放在请求头部）
  secretKey: test_secret_key
  # 数据库节点间数据同步时间间隔
  syncTime: 3
  # 是否为主节点（1:是，0:不是）
  isMaster: 1
