# 服务配置
server:
  # 本地ip
  ip: 127.0.0.1
  # 本地端口
  port: 8012
  # 节点之间数据同步的时间间隔
  syncTime: 2
  # 是否为主节点（1:是，0:不是）
  isMaster: 1

# nacos注册中心配置
nacos:
  ipAddr: VM-8-12-centos
  contextPath: /nacos
  port: 8848
  scheme: http

# 数据库配置
db:
  # 访问密钥（放在请求头部）
  secretKey: test_secret_key
